[package]
name = "webrtc-websys-tests"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
futures = "0.3.28"
getrandom = { version = "0.2.9", features = ["js"] }
multiaddr = { workspace = true }
multihash = { workspace = true }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-bindgen-test = "0.3.37"
web-sys = { version = "0.3.64", features = ["Response", "Window"] }
libp2p-identity = { workspace = true }

[dependencies.libp2p]
path = "../../libp2p"
version = "0.52.1"
features = ["tokio", "noise"]
