[package]
edition = "2021"
license = "MIT"
name = "webrtc-websys-tests"
publish = false
version = "0.1.0"

[dependencies]
console_log = { version = "1.0.0", features = ["wasm-bindgen"] }
fern = { version = "0.6", features = ["colored"] }
futures = "0.3.28"
getrandom = { version = "0.2.9", features = ["js"] }
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true }
libp2p-webrtc-websys = { workspace = true }
log = "0.4.14"
multiaddr = { workspace = true }
multihash = { workspace = true }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-bindgen-test = "0.3.37"
web-sys = { version = "0.3.64", features = ["Response", "Window"] }
