pull_request_rules:
  - name: Ask to resolve conflict
    conditions:
      - conflict
      - -author=dependabot[bot]
      - or:
        - -draft # Don't report conflicts on regular draft.
        - and: # Do report conflicts on draft that are scheduled for the next major release.
          - draft
          - milestone~=v[0-9]\.[0-9]{2}
    actions:
      comment:
        message: This pull request has merge conflicts. Could you please resolve them @{{author}}? 🙏


  - name: Add approved dependabot PRs to merge queue
    conditions:
      # All branch protection rules are implicit: https://docs.mergify.com/conditions/#about-branch-protection
      - author=dependabot[bot]
      - base=master
    actions:
      queue:

  - name: Approve trivial maintainer PRs
    conditions:
      - base=master
      - label=trivial
      - author=@libp2p/rust-libp2p-maintainers
    actions:
      review:

  - name: Approve dependabot PRs of semver-compatible updates
    conditions:
      - author=dependabot[bot]
      - or:
          - title~=bump [^\s]+ from ([1-9]+)\..+ to \1\.      # For major >= 1 versions, only approve updates with the same major version.
          - title~=bump [^\s]+ from 0\.([\d]+)\..+ to 0\.\1\. # For major == 0 versions, only approve updates with the same minor version.
    actions:
      review:
