[package]
name = "libp2p-protocol-utils"
version = "0.1.0"
edition = "2021"
description = "Utilities for implementing protocols for libp2p, via `NetworkBehaviour` and `ConnectionHandler`."
rust-version.workspace = true
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = []
categories = ["data-structures"]
publish = false # Temporary until we actually publish it.

[lints]
workspace = true
