[package]
name = "webrtc-websys-test-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.19"
anyhow = "1.0.72"
futures = "0.3.28"
rand = "0.8"
void = "1"
libp2p-identity = { workspace = true }
tokio = { version = "1.29", features = ["rt", "macros", "signal", "net"] }
tokio-util = { version = "0.7", features = ["compat"] }
tokio-stream = "0.1"
libp2p-webrtc = { workspace = true, features = ["tokio"] }
webrtc-websys-tests = { path = "../" }                                     # for PORT
tower-http = { version = "0.4.0", features = ["cors"] }                    # axum middleware

[dependencies.libp2p]
path = "../../../libp2p"
version = "0.52.1"
features = ["tokio", "noise", "relay", "ping", "macros"]
