[package]
edition = "2021"
license = "MIT"
name = "interop-tests"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
either = "1.9.0"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = "0.6"
libp2p = { path = "../libp2p", features = [
    "dns",
    "identify",
    "macros",
    "noise",
    "ping",
    "quic",
    "rsa",
    "tcp",
    "tls",
    "tokio",
    "websocket",
    "yamux",
] }
libp2p-webrtc = { workspace = true, features = ["tokio"] }
mime_guess = "2.0"
redis = { version = "0.23.0", default-features = false, features = [
    "tokio-comp",
] }
rust-embed = "6.8"
serde_json = "1"
thirtyfour = "=0.32.0-rc.8" # https://github.com/stevepryde/thirtyfour/issues/169
tokio = { version = "1.31.0", features = ["full"] }
tower-http = { version = "0.4", features = ["cors", "fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1.7" }
futures-timer = "3.0.2"
instant = "0.1.12"
libp2p = { path = "../libp2p", features = [
    "identify",
    "macros",
    "ping",
    "wasm-bindgen",
    "webtransport-websys",
] }
libp2p-webrtc-websys = { workspace = true }
reqwest = { version = "0.11", features = ["identify", "json"] }
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = { version = "0.4" }
wasm-logger = { version = "0.2.0" }
