[package]
authors = ["Doug Anderson <douganderson444@peerpiper.io>"]
edition = "2021"
license = "MIT"
name = "browser-webrtc-example-client"
rust-version = { workspace = true }
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
console_log = { version = "1.0", features = ["wasm-bindgen"] }
futures = "0.3.28"
js-sys = "0.3.64"
libp2p = { path = "../../../libp2p", features = [
    "ed25519",
    "macros",
    "ping",
    "wasm-bindgen",
] }
libp2p-webrtc-websys = { workspace = true }
log = "0.4"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.37"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
features = ['Document', 'Element', 'HtmlElement', 'Node', 'Response', 'Window']
version = "0.3"
