[package]
authors = ["Doug Anderson <douganderson444@peerpiper.io>"]
edition = "2021"
license = "MIT"
name = "browser-webrtc-example-client"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
async-channel = "1.9.0"
cfg-if = "0.1"
chrono = { version = "0.4.26", features = ["wasmbind"] }
console_log = { version = "0.2", optional = true }
fern = { version = "0.6.2", features = ["colored"], optional = true }
futures = "0.3.28"
leptos = { version = "0.4.8", features = ["csr", "nightly"] }
libp2p = { path = "../../../libp2p", features = [
    "ed25519",
    "macros",
    "ping",
    "wasm-bindgen",
] }
libp2p-webrtc-websys = { workspace = true }
log = "0.4"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["Response", "Window"] }

[features]
default = ["console_log", "fern"]
