[package]
authors = ["Doug Anderson <douganderson444@peerpiper.io>"]
edition = "2021"
license = "MIT"
name = "webrtc-example-server"
publish = false
rust-version = { workspace = true }
version = "0.1.0"

[[bin]]
name = "webrtc-example-server-bin"
path = "src/bin/webrtc-example-server.rs"

[dependencies]
anyhow = "1.0.72"
axum = "0.6.19"
env_logger = "0.10"
futures = "0.3.28"
libp2p = { path = "../../../libp2p", features = ["ed25519", "identify", "macros", "ping", "relay", "tokio"] }
libp2p-webrtc = { workspace = true, features = ["tokio"] }
log = "0.4"
multiaddr = { workspace = true }
rand = "0.8"
tokio = { version = "1.29", features = ["macros", "net", "rt", "signal"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["compat"] }
tower-http = { version = "0.4.0", features = ["cors", "fs"] }                                                 # axum middleware. fs for static files, cors for CORS
void = "1"
