[package]
name = "libp2p-autonatv2"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
quick-protobuf = "0.8"
quick-protobuf-codec = { workspace = true }
asynchronous-codec = "0.6"
libp2p-core = { workspace = true }
rand_core = "0.6"
rand = { version = "0.8", optional = true }
libp2p-swarm = { workspace = true }
libp2p-identity = { workspace = true }
futures-bounded = { workspace = true }
ip-global = { workspace = true }
void = "1.0.2"
either = "1.9.0"
futures = "0.3.29"
thiserror = "1.0.50"
scc = "2.0.3"
bytes = "1"
static_assertions = "1.1.0"

[lints]
workspace = true

[features]
default = ["rand"]
rand = ["dep:rand"]
