[package]
name = "libp2p-autonatv2"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
quick-protobuf = "0.8"
quick-protobuf-codec = { workspace = true }
asynchronous-codec = "0.7"
libp2p-core = { workspace = true }
rand_core = "0.6"
rand = "0.8"
libp2p-swarm = { workspace = true }
libp2p-identity = { workspace = true }
futures-bounded = { workspace = true }
void = "1.0.2"
either = "1.9.0"
futures = "0.3.29"
thiserror = "1.0.50"
bytes = "1"
static_assertions = "1.1.0"
tracing = "0.1.40"
unsigned-varint = { workspace = true, features = ["futures"] }
futures-timer = "3.0.2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "sync"] }
libp2p-swarm-test = { workspace = true }
libp2p-identify = { workspace = true }
libp2p-swarm = { workspace = true, features = ["macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"]}

[lints]
workspace = true
