[package]
name = "libp2p-webrtc-websys"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
callback-future = "0.1.0" # because web_sys::Rtc is callback based, but we need futures
js-sys = "0.3.64"
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true }
libp2p-noise = { workspace = true }
log = "0.4.19"
hex = "0.4"
getrandom = { version = "0.2.9", features = ["js"] }
multiaddr = { workspace = true }
multihash = { workspace = true }
regex = "1.9.1"
send_wrapper = { version = "0.6.0", features = ["futures"] }
thiserror = "1.0.43"
serde_json = "1.0.103"
sha2 = "0.10.7"
serde = { version = "1.0", features = ["derive"] }
tinytemplate = "1.2.1" # used for the SDP creation
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = [
    "MessageEvent",
    "RtcPeerConnection",
    "RtcSignalingState",
    "RtcSdpType",
    "RtcSessionDescription",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceCandidate",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcCertificate",
    "RtcConfiguration",
    "RtcDataChannelInit",
    "RtcDataChannelType",
    "RtcDataChannelState",
] }

[dev-dependencies]
anyhow = "1.0"
hex-literal = "0.4"
