[package]
name = "libp2p-webrtc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "WebRTC transport for libp2p"
repository = "https://github.com/libp2p/rust-libp2p"
license = ""
edition = "2021"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]
rust-version = "1.56.1"

[dependencies]
bytes = "1"
env_logger = "0.9.0"
futures = "0.3.17"
hex = "0.4"
libp2p-core = { version = "0.33.0", path = "../../core", default-features = false  }
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
tinytemplate = "1.2"
tokio-crate = { package = "tokio", version = "1.17.0", default-features = false, features = ["net"]}
webrtc = { version = "0.4.0", git = "https://github.com/melekes/webrtc", branch = "anton/168-allow-persistent-certificates" }
webrtc-ice = "0.6.6"
webrtc-data = "0.3.3"
webrtc-sctp = "0.4.3"
if-watch = "0.2.2"
futures-timer = "3.0"
stun = "0.4.2"
webrtc-util = { version = "0.5.3", default-features = false, features = ["conn", "vnet", "sync"] }
async-trait = "0.1.52"

[dev-dependencies]
rcgen = "0.8.14"
