[package]
edition = "2021"
name = "libp2p-webrtc-utils"
rust-version.workspace = true
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
futures = "0.3"
hex = "0.4"
js-sys = { version = "0.3", optional = true }
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true }
libp2p-noise = { workspace = true }
log = "0.4.19"
quick-protobuf = "0.8"
quick-protobuf-codec = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.7"
thiserror = "1"
tinytemplate = "1.2"
wasm-bindgen = { version = "0.2.87", optional = true }
web-sys = { version = "0.3.64", optional = true, features = [
    "RtcSdpType",
    "RtcSessionDescription",
    "RtcSessionDescriptionInit",
] }
webrtc = { version = "0.8.0", optional = true }

[features]
tokio = ["dep:webrtc"]
wasm-bindgen = ["dep:js-sys", "dep:wasm-bindgen", "dep:web-sys"]

[dev-dependencies]
hex-literal = "0.4"
