name: Semantic PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@b6bca70dcd3e56e896605356ce09b76f7e1e0d39 # v5.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          # Configure which types are allowed (newline delimited).
          types: |
            feat
            fix
            chore
            docs
            deps
            test
            refactor
            ci
          requireScope: false

      - name: Check PR title length
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          title_length=${#TITLE}
          if [ $title_length -gt 64 ] # Total length should not exceed 72 and we need to reserve 8 for the PR number added by GitHub: ` (#XXXX)`
          then
            echo "PR title is too long (greater than 64 characters)"
            exit 1
          fi
